# Main configuration file for STAMP.
# 
# NOTE: you may use environment variables in this file, e.g. ${oc.env:STAMP_RESOURCES_DIR}.
# The STAMP_RESOURCES_DIR environment variable is a special environment variable that, if not set, will be set to the resources/ directory relative to where STAMP is installed.

# Only use absolute paths!

preprocessing:
  output_dir: /path/to/save/uni/features/ # Path to save features to
  wsi_dir: /path/to/input/WSI/ # Path of where the whole-slide images are.
  cache_dir: # Directory to store intermediate slide JPGs
  microns: 256 # Edge length in microns for each patch (default is 256, with pixel size 224, 256/224 = ~1.14MPP = ~9x magnification)
  norm: false # Perform Macenko normalisation
  feat_extractor: uni # Use ctp for CTransPath (default) or uni for UNI (requires prior authentication)
  del_slide: false # Remove the original slide after processing
  cache: true # Save intermediate images (slide, background rejected, normalized)
  only_feature_extraction: false # Only perform feature extraction (intermediate images (background rejected, [normalized]) have to exist)
  cores: 8 # CPU cores to use
  device: cuda:0 # device to run feature extraction on (cpu, cuda, cuda:0, etc.)